


<table align="center" width="400" border="0" cellpadding="0" cellspacing="0" background="images/pie.jpg">
	<tr>
		<td colspan="2"><div align="right" class="textoBienvenida" >v 24.05.2024.a    </div></td>
	</tr>
</table>



<?php 
global $debug;
//debug:
/*
print_r($_SESSION);
$a= substr_replace("[", "<br>[", $a);
//echo $a;

$a=json_encode($_REQUEST);
//echo "<br>asdfasfasd<br>454534534";
echo $a;
*/

//RESULTADO::   Array ( [usuario] => mikelh [iduser] => 82 [numHospitales] => 14 [idhospital] => 68 [idPerfil] => 6 [hospital] => MAD-Cantoblanco [ipHospital] => cantoblanco.sytes.net [dominioHospital] => cantoblanco.sytes.net [puceTcod] => 18O0X [modoEnvio] => ws [rutaconexion] => cantoblanco.sytes.net/3050:c:\tv\cantoblanco.fdb [ULTIMA_ACTIVIDAD] => 1716509923 [numHabitacion] => [numHabitaciontraslado] => ) 
?>